import { Link } from 'wouter';
import { ArrowUpRight, CalendarDays, ChevronRight, Clock3, FileCheck2, FilePlus2, HeartPulse, MoreHorizontal, ShieldCheck, Stethoscope, UploadCloud } from 'lucide-react';
import { useGetApiPacientesMe, useGetApiDocuments, useGetApiDocumentsCount } from '@workspace/api-client-react';

const typeLabel: Record<string, string> = { exame: 'Exame', receita: 'Receita', laudo: 'Laudo' };

export default function Dashboard() {
  const { data: profile, isLoading: profileLoading } = useGetApiPacientesMe();
  const { data: documentsRaw, isLoading: docsLoading } = useGetApiDocuments();
  const { data: countRaw } = useGetApiDocumentsCount();

  const user = profile as unknown as any;
  const documents = (documentsRaw as unknown as any[]) || [];
  const count = (countRaw as unknown as any) || { total: 0, exames: 0, receitas: 0, laudos: 0, receitasAtivas: 0 };
  
  const recent = documents.slice(0, 3);

  if (profileLoading || docsLoading) {
    return <div className="page-enter p-12 text-center text-muted-foreground">Carregando seus dados...</div>;
  }

  if (!user) {
    return <div className="page-enter p-12 text-center text-red-500">Falha ao carregar perfil. Faça login novamente.</div>;
  }

  return <div className="page-enter space-y-8">
    <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">visão geral</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.06em] text-foreground md:text-[40px]">Olá, {user.nome?.split(' ')[0]}.</h1><p className="mt-2 text-sm text-muted-foreground">Seu histórico de saúde, com mais clareza para hoje.</p></div><Link href="/upload" className="group flex w-fit items-center gap-2 rounded-xl bg-primary px-4 py-3 text-xs font-bold text-primary-foreground transition-all hover:-translate-y-0.5 hover:shadow-lg"><UploadCloud size={16} /> Adicionar documento <ArrowUpRight size={15} className="transition-transform group-hover:translate-x-0.5" /></Link></section>
    <section className="grid gap-4 md:grid-cols-[1.35fr_.65fr]">
      <div className="relative overflow-hidden rounded-2xl bg-primary p-6 text-primary-foreground soft-shadow md:p-8"><div className="absolute -right-8 -top-20 h-64 w-64 rounded-full border border-white/10" /><div className="absolute -right-2 -top-5 h-40 w-40 rounded-full border border-white/10" /><div className="relative"><div className="flex items-center justify-between"><span className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.17em] text-white/60"><HeartPulse size={14} className="text-[hsl(var(--sidebar-primary))]" /> seu resumo</span><ShieldCheck size={18} className="text-[hsl(var(--sidebar-primary))]" /></div><h2 className="mt-8 max-w-[390px] text-2xl font-extrabold leading-tight tracking-[-.045em] md:text-3xl">Sua saúde está organizada para quando você precisar.</h2><p className="mt-3 max-w-[410px] text-[13px] leading-6 text-white/62">Você tem <strong className="text-white">{count.total} documentos</strong> guardados e um histórico pronto para acompanhar sua próxima conversa médica.</p><div className="mt-8 flex items-center gap-5"><div><p className="font-mono text-[23px] text-white">{count.exames}</p><p className="mt-1 text-[10px] text-white/48">exames</p></div><div className="h-8 w-px bg-white/15" /><div><p className="font-mono text-[23px] text-white">{count.receitas}</p><p className="mt-1 text-[10px] text-white/48">receitas</p></div><div className="h-8 w-px bg-white/15" /><div><p className="font-mono text-[23px] text-white">{count.receitasAtivas}</p><p className="mt-1 text-[10px] text-white/48">ativas</p></div></div></div></div>
      <Link href="/record" className="group relative overflow-hidden rounded-2xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:shadow-[var(--shadow-lift)]"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-secondary text-accent"><Stethoscope size={19} /></span><ArrowUpRight size={17} className="text-muted-foreground transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></div><div className="mt-12"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-muted-foreground">minha anamnese</p><h3 className="mt-2 text-xl font-extrabold tracking-[-.045em]">Seu contexto importa.</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">Mantenha seu histórico pessoal atualizado para consultas mais completas.</p></div><div className="mt-5 flex items-center gap-2 text-[11px] font-bold text-primary">Revisar informações <ChevronRight size={14} /></div></Link>
    </section>
    <section className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]">
      <div className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.17em] text-muted-foreground">últimos documentos</p><h2 className="mt-1 text-lg font-extrabold tracking-[-.035em]">O que entrou recentemente</h2></div><Link href="/documents" className="text-[11px] font-bold text-primary hover:text-accent">Ver todos</Link></div><div className="mt-5 divide-y divide-border/70">{recent.length === 0 ? <p className="text-sm text-muted-foreground">Nenhum documento ainda.</p> : recent.map((doc: any) => <Link href={`/documents/${doc.id}`} key={doc.id} className="group flex items-center gap-3 py-4 first:pt-0 last:pb-0"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${doc.type === 'receita' ? 'bg-[hsl(39_85%_92%)] text-[hsl(34_73%_42%)]' : doc.type === 'laudo' ? 'bg-[hsl(205_72%_93%)] text-primary' : 'bg-secondary text-accent'}`}><FileCheck2 size={18} /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="truncate text-[13px] font-bold group-hover:text-primary">{doc.title}</span><span className="hidden rounded-full bg-muted px-2 py-0.5 text-[9px] font-bold text-muted-foreground sm:inline">{typeLabel[doc.type] || doc.type}</span></span><span className="mt-1 block text-[11px] text-muted-foreground">{doc.doctor} · {new Date(doc.createdAt).toLocaleDateString('pt-BR')}</span></span><ChevronRight size={16} className="text-muted-foreground/50 transition-transform group-hover:translate-x-1" /></Link>)}</div></div>
      <div className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.17em] text-muted-foreground">linha do tempo</p><h2 className="mt-1 text-lg font-extrabold tracking-[-.035em]">Sua atividade</h2></div><button className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><MoreHorizontal size={17} /></button></div><div className="mt-5 space-y-5">
        {documents.slice(0, 4).map((activity: any, index: number) => <div className="flex gap-3" key={activity.id}><div className="relative flex w-7 justify-center"><span className={`relative z-10 mt-1.5 h-2 w-2 rounded-full ${index === 0 ? 'bg-accent' : 'bg-border'}`} />{index < 3 && <span className="absolute top-3 h-full w-px bg-border/70" />}</div><div className="min-w-0"><p className="text-[12px] font-semibold leading-5">{activity.title} adicionado</p><p className="mt-0.5 flex items-center gap-1 text-[10px] text-muted-foreground"><Clock3 size={11} /> {new Date(activity.createdAt).toLocaleDateString('pt-BR')}</p></div></div>)}
      </div></div>
    </section>
    <section className="flex flex-col gap-4 rounded-2xl border border-dashed border-accent/40 bg-[hsl(var(--secondary)/.45)] p-5 md:flex-row md:items-center md:justify-between md:p-6"><div className="flex items-center gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-card text-accent soft-shadow"><FilePlus2 size={20} /></span><div><p className="text-sm font-extrabold">Tem um documento novo?</p><p className="mt-1 text-xs text-muted-foreground">Uma foto ou PDF já é suficiente. A gente organiza o resto.</p></div></div><Link href="/upload" className="flex w-fit items-center gap-2 rounded-xl border border-primary/20 bg-card px-4 py-2.5 text-xs font-bold text-primary hover:border-primary/40"><CalendarDays size={15} /> Fazer upload</Link></section>
  </div>;
}